[package]
name = "edge-inference"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tract = "0.22.0"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
lto = true
